### ISSUE TITLE
Segfault in moveit_rviz_plugin::MotionPlanningDisplay::fixedFrameChanged()

### ISSUE THREAD

**Issue by wshackle** [ros-planning/moveit2#1942]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22.04
* Source or Binary build? See instructions below
* If binary, which release version?
* If source, which branch?
* Which RMW (Fast DDS or Cyclone DDS)? Cyclone 

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.
Setup tutorial as described in https://moveit.picknik.ai/humble/doc/tutorials/getting_started/getting_started.html
Start tutorial as described in https://moveit.picknik.ai/humble/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html
Run the following command in a separate terminal
    
    ros2 launch moveit2_tutorials demo.launch.py rviz_tutorial:=true

(Note rviz2 doesn't start)

Run rviz2 in a new terminal
Add the MotionPlanning visualization
Change the fixed frame under GlobalOptions from map to panda_link0

### Expected behaviour
rviz2 should not crash

### Actual behaviour
Rviz2 has a segfault

### Backtrace or Console output

The console output of rviz2 : 

It starts with:

        shackle@SQUALL:~/ws_moveit2$ rviz2
        Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
        [INFO] [1675960123.345118122] [rviz2]: Stereo is NOT SUPPORTED
        [INFO] [1675960123.345166914] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
        [INFO] [1675960123.356433030] [rviz2]: Stereo is NOT SUPPORTED
        Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
                 at line 253 in /opt/ros/humble/include/class_loader/class_loader/class_loader_core.hpp
        [ERROR] [1675960147.410762839] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
        [INFO] [1675960147.431291771] [moveit_ros_visualization.motion_planning_frame]: MoveGroup namespace changed: / -> . Reloading params.
        [INFO] [1675960147.775675969] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.321374 seconds
        [INFO] [1675960147.775752140] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
        [WARN] [1675960147.791543145] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!
        [INFO] [1675960147.806967128] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
        [INFO] [1675960147.807621716] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/monitored_planning_scene'
        [INFO] [1675960147.983762700] [interactive_marker_display_93940753848528]: Connected on namespace: /rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic
        [INFO] [1675960147.985190855] [moveit_ros_robot_interaction.robot_interaction]: No active joints or end effectors found for group 'hand'. Make sure that kinematics.yaml is loaded in this node's namespace.
        [INFO] [1675960147.985556628] [moveit_ros_robot_interaction.robot_interaction]: No active joints or end effectors found for group 'hand'. Make sure that kinematics.yaml is loaded in this node's namespace.
        Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
                 at line 93 in ./src/buffer_core.cpp
        [INFO] [1675960147.988286085] [moveit_ros_visualization.motion_planning_frame]: group hand
        [INFO] [1675960147.988297438] [moveit_ros_visualization.motion_planning_frame]: Constructing new MoveGroup connection for group 'hand' in namespace ''
        [INFO] [1675960147.991850279] [move_group_interface]: Ready to take commands for planning group hand.
        [INFO] [1675960147.992332211] [moveit_ros_visualization.motion_planning_frame]: group hand
 
Then repeats many times:

        [INFO] [1675960147.993276277] [interactive_marker_display_93940753848528]: Sending request for interactive markers
        Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
                 at line 93 in ./src/buffer_core.cpp

Then ends with:

        
        [INFO] [1675960164.496615239] [interactive_marker_display_93940753848528]: Target frame is now panda_link0
        Segmentation fault (core dumped)
        shackle@SQUALL:~/ws_moveit2$ 

The console output of ros2 launch moveit2_tutorials demo.launch.py rviz_tutorial:=true :

        ros2 launch moveit2_tutorials demo.launch.py rviz_tutorial:=true
        [INFO] [launch]: All log files can be found below /home/isd/shackle/.ros/log/2023-02-09-10-58-39-205158-SQUALL-5250
        [INFO] [launch]: Default logging verbosity is set to INFO
        [INFO] [static_transform_publisher-1]: process started with pid [5254]
        [INFO] [robot_state_publisher-2]: process started with pid [5256]
        [INFO] [move_group-3]: process started with pid [5258]
        [INFO] [ros2_control_node-4]: process started with pid [5260]
        [INFO] [spawner-5]: process started with pid [5262]
        [INFO] [spawner-6]: process started with pid [5264]
        [INFO] [spawner-7]: process started with pid [5266]
        [static_transform_publisher-1] [WARN] [1675958319.523134362] []: Old-style arguments are deprecated; see --help for new-style arguments
        [static_transform_publisher-1] [INFO] [1675958319.531174928] [static_transform_publisher]: Spinning until stopped - publishing transform
        [static_transform_publisher-1] translation: ('0.000000', '0.000000', '0.000000')
        [static_transform_publisher-1] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
        [static_transform_publisher-1] from 'world' to 'panda_link0'
        [robot_state_publisher-2] [INFO] [1675958319.535389782] [robot_state_publisher]: got segment panda_hand
        [robot_state_publisher-2] [INFO] [1675958319.535475562] [robot_state_publisher]: got segment panda_leftfinger
        [robot_state_publisher-2] [INFO] [1675958319.535489657] [robot_state_publisher]: got segment panda_link0
        [robot_state_publisher-2] [INFO] [1675958319.535499802] [robot_state_publisher]: got segment panda_link1
        [robot_state_publisher-2] [INFO] [1675958319.535508683] [robot_state_publisher]: got segment panda_link2
        [robot_state_publisher-2] [INFO] [1675958319.535517193] [robot_state_publisher]: got segment panda_link3
        [robot_state_publisher-2] [INFO] [1675958319.535525609] [robot_state_publisher]: got segment panda_link4
        [robot_state_publisher-2] [INFO] [1675958319.535534235] [robot_state_publisher]: got segment panda_link5
        [robot_state_publisher-2] [INFO] [1675958319.535542445] [robot_state_publisher]: got segment panda_link6
        [robot_state_publisher-2] [INFO] [1675958319.535550669] [robot_state_publisher]: got segment panda_link7
        [robot_state_publisher-2] [INFO] [1675958319.535558968] [robot_state_publisher]: got segment panda_link8
        [robot_state_publisher-2] [INFO] [1675958319.535567302] [robot_state_publisher]: got segment panda_rightfinger
        [ros2_control_node-4] [INFO] [1675958319.544086772] [resource_manager]: Loading hardware 'PandaFakeSystem' 
        [ros2_control_node-4] [INFO] [1675958319.544895336] [resource_manager]: Initialize hardware 'PandaFakeSystem' 
        [ros2_control_node-4] [WARN] [1675958319.544934734] [mock_generic_system]: Parsing of optional initial interface values failed or uses a deprecated format. Add initial values for every state interface in the ros2_control.xacro. For example: 
        [ros2_control_node-4] <state_interface name="velocity"> 
        [ros2_control_node-4]   <param name="initial_value">0.0</param> 
        [ros2_control_node-4] </state_interface>
        [ros2_control_node-4] [INFO] [1675958319.544947592] [resource_manager]: Successful initialization of hardware 'PandaFakeSystem'
        [ros2_control_node-4] [INFO] [1675958319.544970583] [resource_manager]: Loading hardware 'PandaHandFakeSystem' 
        [ros2_control_node-4] [INFO] [1675958319.544982102] [resource_manager]: Initialize hardware 'PandaHandFakeSystem' 
        [ros2_control_node-4] [INFO] [1675958319.544993353] [resource_manager]: Successful initialization of hardware 'PandaHandFakeSystem'
        [ros2_control_node-4] [INFO] [1675958319.545023500] [resource_manager]: 'configure' hardware 'PandaFakeSystem' 
        [ros2_control_node-4] [INFO] [1675958319.545029172] [resource_manager]: Successful 'configure' of hardware 'PandaFakeSystem'
        [ros2_control_node-4] [INFO] [1675958319.545037217] [resource_manager]: 'activate' hardware 'PandaFakeSystem' 
        [ros2_control_node-4] [INFO] [1675958319.545042274] [resource_manager]: Successful 'activate' of hardware 'PandaFakeSystem'
        [ros2_control_node-4] [INFO] [1675958319.545046786] [resource_manager]: 'configure' hardware 'PandaHandFakeSystem' 
        [ros2_control_node-4] [INFO] [1675958319.545050855] [resource_manager]: Successful 'configure' of hardware 'PandaHandFakeSystem'
        [ros2_control_node-4] [INFO] [1675958319.545055938] [resource_manager]: 'activate' hardware 'PandaHandFakeSystem' 
        [ros2_control_node-4] [INFO] [1675958319.545059880] [resource_manager]: Successful 'activate' of hardware 'PandaHandFakeSystem'
        [ros2_control_node-4] [INFO] [1675958319.547723876] [controller_manager]: update rate is 100 Hz
        [ros2_control_node-4] [INFO] [1675958319.547897099] [controller_manager]: RT kernel is recommended for better performance
        [move_group-3] [INFO] [1675958319.571460458] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0029337 seconds
        [move_group-3] [INFO] [1675958319.571602512] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
        [move_group-3] [INFO] [1675958319.605178094] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
        [move_group-3] [INFO] [1675958319.605314108] [moveit.ros_planning_interface.moveit_cpp]: Listening to 'joint_states' for joint states
        [move_group-3] [INFO] [1675958319.606158585] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
        [move_group-3] [INFO] [1675958319.606494051] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
        [move_group-3] [INFO] [1675958319.606502355] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
        [move_group-3] [INFO] [1675958319.606920446] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/planning_scene'
        [move_group-3] [INFO] [1675958319.606925942] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
        [move_group-3] [INFO] [1675958319.607071828] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
        [move_group-3] [INFO] [1675958319.607232930] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
        [move_group-3] [WARN] [1675958319.608122348] [moveit.ros.occupancy_map_monitor.middleware_handle]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
        [move_group-3] [ERROR] [1675958319.608131831] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
        [move_group-3] [INFO] [1675958319.608480508] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'ompl'
        [move_group-3] [INFO] [1675958319.632787825] [moveit.ros_planning.planning_pipeline]: Using planning interface 'OMPL'
        [move_group-3] [INFO] [1675958319.636355694] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.path_tolerance' was not set. Using default value: 0.100000
        [move_group-3] [INFO] [1675958319.636369218] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.resample_dt' was not set. Using default value: 0.100000
        [move_group-3] [INFO] [1675958319.636372323] [moveit_ros.add_time_optimal_parameterization]: Param 'ompl.min_angle_change' was not set. Using default value: 0.001000
        [move_group-3] [INFO] [1675958319.636390514] [moveit_ros.fix_workspace_bounds]: Param 'ompl.default_workspace_bounds' was not set. Using default value: 10.000000
        [move_group-3] [INFO] [1675958319.636399671] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_bounds_error' was set to 0.100000
        [move_group-3] [INFO] [1675958319.636403079] [moveit_ros.fix_start_state_bounds]: Param 'ompl.start_state_max_dt' was not set. Using default value: 0.500000
        [move_group-3] [INFO] [1675958319.636409426] [moveit_ros.fix_start_state_collision]: Param 'ompl.start_state_max_dt' was not set. Using default value: 0.500000
        [move_group-3] [INFO] [1675958319.636412009] [moveit_ros.fix_start_state_collision]: Param 'ompl.jiggle_fraction' was not set. Using default value: 0.020000
        [move_group-3] [INFO] [1675958319.636420167] [moveit_ros.fix_start_state_collision]: Param 'ompl.max_sampling_attempts' was not set. Using default value: 100
        [move_group-3] [INFO] [1675958319.636426627] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
        [move_group-3] [INFO] [1675958319.636429787] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Resolve constraint frames to robot links'
        [move_group-3] [INFO] [1675958319.636431468] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
        [move_group-3] [INFO] [1675958319.636433278] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
        [move_group-3] [INFO] [1675958319.636434896] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
        [move_group-3] [INFO] [1675958319.636436520] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
        [move_group-3] [INFO] [1675958319.637544447] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'chomp'
        [move_group-3] [INFO] [1675958319.644047088] [moveit.ros_planning.planning_pipeline]: Using planning interface 'CHOMP'
        [move_group-3] [INFO] [1675958319.645955727] [moveit_ros.add_time_optimal_parameterization]: Param 'chomp.path_tolerance' was not set. Using default value: 0.100000
        [move_group-3] [INFO] [1675958319.645968638] [moveit_ros.add_time_optimal_parameterization]: Param 'chomp.resample_dt' was not set. Using default value: 0.100000
        [move_group-3] [INFO] [1675958319.645971938] [moveit_ros.add_time_optimal_parameterization]: Param 'chomp.min_angle_change' was not set. Using default value: 0.001000
        [move_group-3] [INFO] [1675958319.645981303] [moveit_ros.fix_workspace_bounds]: Param 'chomp.default_workspace_bounds' was not set. Using default value: 10.000000
        [move_group-3] [INFO] [1675958319.645991395] [moveit_ros.fix_start_state_bounds]: Param 'chomp.start_state_max_bounds_error' was set to 0.100000
        [move_group-3] [INFO] [1675958319.645994294] [moveit_ros.fix_start_state_bounds]: Param 'chomp.start_state_max_dt' was not set. Using default value: 0.500000
        [move_group-3] [INFO] [1675958319.646001875] [moveit_ros.fix_start_state_collision]: Param 'chomp.start_state_max_dt' was not set. Using default value: 0.500000
        [move_group-3] [INFO] [1675958319.646004612] [moveit_ros.fix_start_state_collision]: Param 'chomp.jiggle_fraction' was not set. Using default value: 0.020000
        [move_group-3] [INFO] [1675958319.646007499] [moveit_ros.fix_start_state_collision]: Param 'chomp.max_sampling_attempts' was not set. Using default value: 100
        [move_group-3] [INFO] [1675958319.646014063] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
        [move_group-3] [INFO] [1675958319.646016878] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
        [move_group-3] [INFO] [1675958319.646018999] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
        [move_group-3] [INFO] [1675958319.646020765] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
        [move_group-3] [INFO] [1675958319.646022592] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
        [move_group-3] [INFO] [1675958319.646554852] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'pilz_industrial_motion_planner'
        [move_group-3] [INFO] [1675958319.649638893] [moveit.pilz_industrial_motion_planner.joint_limits_aggregator]: Reading limits from namespace robot_description_planning
        [move_group-3] [WARN] [1675958319.649968938] [moveit.pilz_industrial_motion_planner.joint_limits_aggregator]: Multi-DOF-Joint 'virtual_joint' not supported.
        [move_group-3] [WARN] [1675958319.649981983] [moveit.pilz_industrial_motion_planner.joint_limits_aggregator]: Multi-DOF-Joint 'virtual_joint' not supported.
        [move_group-3] [INFO] [1675958319.652096522] [moveit.pilz_industrial_motion_planner]: Available plugins: pilz_industrial_motion_planner/PlanningContextLoaderCIRC pilz_industrial_motion_planner/PlanningContextLoaderLIN pilz_industrial_motion_planner/PlanningContextLoaderPTP 
        [move_group-3] [INFO] [1675958319.652108915] [moveit.pilz_industrial_motion_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderCIRC
        [move_group-3] [INFO] [1675958319.653840743] [moveit.pilz_industrial_motion_planner]: Registered Algorithm [CIRC]
        [move_group-3] [INFO] [1675958319.653851161] [moveit.pilz_industrial_motion_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderLIN
        [move_group-3] [INFO] [1675958319.654681450] [moveit.pilz_industrial_motion_planner]: Registered Algorithm [LIN]
        [move_group-3] [INFO] [1675958319.654690533] [moveit.pilz_industrial_motion_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderPTP
        [move_group-3] [INFO] [1675958319.655610134] [moveit.pilz_industrial_motion_planner]: Registered Algorithm [PTP]
        [move_group-3] [INFO] [1675958319.655625998] [moveit.ros_planning.planning_pipeline]: Using planning interface 'Pilz Industrial Motion Planner'
        [move_group-3] [INFO] [1675958319.657154617] [moveit_ros.fix_workspace_bounds]: Param 'pilz_industrial_motion_planner.default_workspace_bounds' was not set. Using default value: 10.000000
        [move_group-3] [INFO] [1675958319.657169032] [moveit_ros.fix_start_state_bounds]: Param 'pilz_industrial_motion_planner.start_state_max_bounds_error' was not set. Using default value: 0.050000
        [move_group-3] [INFO] [1675958319.657184024] [moveit_ros.fix_start_state_bounds]: Param 'pilz_industrial_motion_planner.start_state_max_dt' was not set. Using default value: 0.500000
        [move_group-3] [INFO] [1675958319.657191863] [moveit_ros.fix_start_state_collision]: Param 'pilz_industrial_motion_planner.start_state_max_dt' was not set. Using default value: 0.500000
        [move_group-3] [INFO] [1675958319.657194396] [moveit_ros.fix_start_state_collision]: Param 'pilz_industrial_motion_planner.jiggle_fraction' was not set. Using default value: 0.020000
        [move_group-3] [INFO] [1675958319.657197468] [moveit_ros.fix_start_state_collision]: Param 'pilz_industrial_motion_planner.max_sampling_attempts' was not set. Using default value: 100
        [move_group-3] [INFO] [1675958319.657204365] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
        [move_group-3] [INFO] [1675958319.657207238] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
        [move_group-3] [INFO] [1675958319.657208929] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
        [move_group-3] [INFO] [1675958319.657210573] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
        [ros2_control_node-4] [INFO] [1675958319.662831355] [controller_manager]: Loading controller 'panda_arm_controller'
        [ros2_control_node-4] [INFO] [1675958319.669012204] [joint_trajectory_controller.interpolation_methods]: No interpolation method parameter was given. Using the default, VARIABLE_DEGREE_SPLINE.
        [move_group-3] [INFO] [1675958319.669843825] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for panda_arm_controller
        [move_group-3] [INFO] [1675958319.669878553] [moveit.plugins.moveit_simple_controller_manager]: Max effort set to 0.0
        [move_group-3] [INFO] [1675958319.670328615] [moveit.plugins.moveit_simple_controller_manager]: Added GripperCommand controller for panda_hand_controller
        [move_group-3] [INFO] [1675958319.670409599] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
        [move_group-3] [INFO] [1675958319.670432891] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
        [move_group-3] [INFO] [1675958319.670540153] [moveit_ros.trajectory_execution_manager]: Trajectory execution is managing controllers
        [move_group-3] [INFO] [1675958319.670545990] [move_group.move_group]: MoveGroup debug mode is ON
        [ros2_control_node-4] [INFO] [1675958319.678981071] [controller_manager]: Loading controller 'panda_hand_controller'
        [move_group-3] [INFO] [1675958319.682988897] [move_group.move_group]: 
        [move_group-3] 
        [move_group-3] ********************************************************
        [move_group-3] * MoveGroup using: 
        [move_group-3] *     - ApplyPlanningSceneService
        [move_group-3] *     - ClearOctomapService
        [move_group-3] *     - CartesianPathService
        [move_group-3] *     - ExecuteTrajectoryAction
        [move_group-3] *     - GetPlanningSceneService
        [move_group-3] *     - KinematicsService
        [move_group-3] *     - MoveAction
        [move_group-3] *     - MotionPlanService
        [move_group-3] *     - QueryPlannersService
        [move_group-3] *     - StateValidationService
        [move_group-3] ********************************************************
        [move_group-3] 
        [move_group-3] [INFO] [1675958319.683019254] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
        [move_group-3] [INFO] [1675958319.683025829] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context initialization complete
        [move_group-3] Loading 'move_group/ApplyPlanningSceneService'...
        [move_group-3] Loading 'move_group/ClearOctomapService'...
        [move_group-3] Loading 'move_group/MoveGroupCartesianPathService'...
        [move_group-3] Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
        [move_group-3] Loading 'move_group/MoveGroupGetPlanningSceneService'...
        [move_group-3] Loading 'move_group/MoveGroupKinematicsService'...
        [move_group-3] Loading 'move_group/MoveGroupMoveAction'...
        [move_group-3] Loading 'move_group/MoveGroupPlanService'...
        [move_group-3] Loading 'move_group/MoveGroupQueryPlannersService'...
        [move_group-3] Loading 'move_group/MoveGroupStateValidationService'...
        [move_group-3] 
        [move_group-3] You can start planning now!
        [move_group-3] 
        [ros2_control_node-4] [INFO] [1675958319.688107489] [controller_manager]: Loading controller 'joint_state_broadcaster'
        [spawner-6] [INFO] [1675958319.688135364] [spawner_panda_arm_controller]: Loaded panda_arm_controller
        [spawner-7] [INFO] [1675958319.693698212] [spawner_panda_hand_controller]: Loaded panda_hand_controller
        [ros2_control_node-4] [INFO] [1675958319.698432600] [controller_manager]: Configuring controller 'panda_arm_controller'
        [ros2_control_node-4] [INFO] [1675958319.698559911] [panda_arm_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
        [ros2_control_node-4] [INFO] [1675958319.698602010] [panda_arm_controller]: Command interfaces are [position] and state interfaces are [position velocity].
        [ros2_control_node-4] [INFO] [1675958319.698631008] [joint_trajectory_controller.interpolation_methods]: No interpolation method parameter was given. Using the default, VARIABLE_DEGREE_SPLINE.
        [ros2_control_node-4] [INFO] [1675958319.698638725] [panda_arm_controller]: Using 'splines' interpolation method.
        [ros2_control_node-4] [INFO] [1675958319.699715461] [panda_arm_controller]: Controller state will be published at 50.00 Hz.
        [ros2_control_node-4] [INFO] [1675958319.701007264] [panda_arm_controller]: Action status changes will be monitored at 20.00 Hz.
        [ros2_control_node-4] [INFO] [1675958319.702402846] [controller_manager]: Configuring controller 'panda_hand_controller'
        [ros2_control_node-4] [INFO] [1675958319.702490978] [panda_hand_controller]: Action status changes will be monitored at 20Hz.
        [spawner-5] [INFO] [1675958319.706063563] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
        [ros2_control_node-4] [INFO] [1675958319.718559662] [controller_manager]: Configuring controller 'joint_state_broadcaster'
        [ros2_control_node-4] [INFO] [1675958319.718619269] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
        [spawner-6] [INFO] [1675958319.719205493] [spawner_panda_arm_controller]: Configured and activated panda_arm_controller
        [spawner-7] [INFO] [1675958319.739308637] [spawner_panda_hand_controller]: Configured and activated panda_hand_controller
        [spawner-5] [INFO] [1675958319.759347938] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
        [INFO] [spawner-6]: process has finished cleanly [pid 5264]
        [INFO] [spawner-7]: process has finished cleanly [pid 5266]
        [INFO] [spawner-5]: process has finished cleanly [pid 5262]

The backtrace was:

        (gdb) bt
        #0  0x00007efd54620a40 in moveit_rviz_plugin::MotionPlanningDisplay::fixedFrameChanged() ()
            at /home/isd/shackle/ws_moveit2/install/moveit_ros_visualization/lib/libmoveit_motion_planning_rviz_plugin_core.so.2.5.4
        #1  0x00007efe0a053d07 in rviz_common::DisplayGroup::fixedFrameChanged() () at /opt/ros/humble/lib/librviz_common.so
        #2  0x00007efe0a0af490 in rviz_common::VisualizationManager::updateFixedFrame() () at /opt/ros/humble/lib/librviz_common.so
        #3  0x00007efe096337c8 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
        #4  0x00007efe0a07064b in rviz_common::properties::Property::setValue(QVariant const&) () at /opt/ros/humble/lib/librviz_common.so
        #5  0x00007efe0a075904 in rviz_common::properties::TfFrameProperty::setValue(QVariant const&) () at /opt/ros/humble/lib/librviz_common.so
        #6  0x00007efe0a023249 in  () at /opt/ros/humble/lib/librviz_common.so
        #7  0x00007efe096337c8 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
        #8  0x00007efe09b151c9 in QComboBox::currentIndexChanged(QString const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #9  0x00007efe09b17a71 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #10 0x00007efe09b1a575 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #11 0x00007efe09b1a79d in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #12 0x00007efe096337c8 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
        #13 0x00007efe09b154c6 in QComboBoxPrivateContainer::itemSelected(QModelIndex const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #14 0x00007efe09b15df0 in QComboBoxPrivateContainer::eventFilter(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #15 0x00007efe095fbb9a in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
        #16 0x00007efe09a0d702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #17 0x00007efe09a15364 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #18 0x00007efe095fbe3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
        #19 0x00007efe09a13e47 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #20 0x00007efe09a6a843 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #21 0x00007efe09a6cfd5 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #22 0x00007efe09a0d713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
        #23 0x00007efe095fbe3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
        #24 0x00007efe082a4307 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
        #25 0x00007efe08279a2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
        #26 0x00007efe03001d6e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
        #27 0x00007efe07890d3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
        #28 0x00007efe078e56c8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
        #29 0x00007efe0788e3e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
        #30 0x00007efe096550b8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
        #31 0x00007efe095fa75b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
        #32 0x00007efe09602cf4 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
        #33 0x0000559aef07199e in  ()
        #34 0x00007efe08cecd90 in __libc_start_call_main (main=main@entry=0x559aef071430, argc=argc@entry=1, argv=argv@entry=0x7ffc13b9dba8) at ../sysdeps/nptl/libc_start_call_main.h:58
        #35 0x00007efe08cece40 in __libc_start_main_impl (main=0x559aef071430, argc=1, argv=0x7ffc13b9dba8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc13b9db98)
            at ../csu/libc-start.c:392
        #36 0x0000559aef071c15 in  ()

**Comment by breezZe** [comment]
I have the same issue.

**Comment by breezZe** [comment]
@wshackle I've got a method to work around this. 
Set ```fixed_frame``` to ```/panda_link0``` as soon as RVIZ2 started, then launch moveit tutorial node will work. RVIZ2 will not crash. Maybe you can try it. I still don't know the reason, however I think it is a rviz2 problem but not moveit?
