### ISSUE TITLE
[foxy] moveit_core is failing to build on buildfarm

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit2#951]
https://build.ros2.org/job/Fbin_uF64__moveit_core__ubuntu_focal_amd64__binary/73/console

```
23:10:11 /usr/bin/ld: ../utils/libmoveit_test_utils.so.2.2.2: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&)'
23:10:12 /usr/bin/ld: ../utils/libmoveit_test_utils.so.2.2.2: undefined reference to `boost::re_detail_107100::put_mem_block(void*)'
23:10:12 /usr/bin/ld: ../utils/libmoveit_test_utils.so.2.2.2: undefined reference to `boost::re_detail_107100::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
23:10:12 /usr/bin/ld: ../utils/libmoveit_test_utils.so.2.2.2: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
23:10:12 /usr/bin/ld: ../utils/libmoveit_test_utils.so.2.2.2: undefined reference to `boost::re_detail_107100::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
23:10:12 /usr/bin/ld: ../utils/libmoveit_test_utils.so.2.2.2: undefined reference to `boost::re_detail_107100::get_default_error_string(boost::regex_constants::error_type)'
23:10:12 /usr/bin/ld: ../utils/libmoveit_test_utils.so.2.2.2: undefined reference to `boost::re_detail_107100::raise_runtime_error(std::runtime_error const&)'
23:10:12 /usr/bin/ld: ../utils/libmoveit_test_utils.so.2.2.2: undefined reference to `boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int)'
23:10:12 /usr/bin/ld: ../utils/libmoveit_test_utils.so.2.2.2: undefined reference to `boost::re_detail_107100::verify_options(unsigned int, boost::regex_constants::_match_flags)'
23:10:12 /usr/bin/ld: ../utils/libmoveit_test_utils.so.2.2.2: undefined reference to `boost::re_detail_107100::get_mem_block()'
23:10:12 collect2: error: ld returned 1 exit status
23:10:12 make[4]: *** [robot_model/CMakeFiles/test_robot_model.dir/build.make:213: robot_model/test_robot_model] Error 1
23:10:12 make[4]: Leaving directory '/tmp/binarydeb/ros-foxy-moveit-core-2.2.2/obj-x86_64-linux-gnu'
23:10:12 make[3]: *** [CMakeFiles/Makefile2:951: robot_model/CMakeFiles/test_robot_model.dir/all] Error 2
23:10:12 make[3]: Leaving directory '/tmp/binarydeb/ros-foxy-moveit-core-2.2.2/obj-x86_64-linux-gnu'
23:10:12 make[2]: Leaving directory '/tmp/binarydeb/ros-foxy-moveit-core-2.2.2/obj-x86_64-linux-gnu'
23:10:12 make[2]: *** [Makefile:144: all] Error 2
23:10:12 dh_auto_build: error: cd obj-x86_64-linux-gnu && make -j1 returned exit code 2
23:10:12 make[1]: Leaving directory '/tmp/binarydeb/ros-foxy-moveit-core-2.2.2'
23:10:12 make[1]: *** [debian/rules:38: override_dh_auto_build] Error 25
23:10:12 make: *** [debian/rules:22: build] Error 2
23:10:12 dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
23:10:12 E: Building failed
23:10:12 Traceback (most recent call last):
23:10:12   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 147, in build_binarydeb
23:10:12     subprocess.check_call(cmd, cwd=source_dir, env=env)
23:10:12   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
23:10:12     raise CalledProcessError(retcode, cmd)
23:10:12 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-foxy-moveit-core']' returned non-zero exit status 1.
23:10:12 # END SUBSECTION
```

**Comment by vatanaksoytezer** [comment]
Closed by #977. Foxy builds are now passing.
